_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 49
                - 55
                - 105
            "2":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 49
                - 55
                - 80
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
artifact_alias:
    value: latest
batch_size:
    value: 16
bbox_interval:
    value: -1
bucket:
    value: ""
cache:
    value: null
cfg:
    value: models/detect/gelan-c.yaml
close_mosaic:
    value: 15
cos_lr:
    value: false
data:
    value: /content/yolov9/k3/data.yaml
data_dict:
    value:
        names:
            "0": fortification
            "1": infantry
            "2": vehicle
        nc: 3
        path: /content/yolov9
        roboflow:
            license: CC BY 4.0
            project: military-vehicles-awjcr
            url: https://universe.roboflow.com/jellywoon-xzc5r/military-vehicles-awjcr/dataset/3
            version: 3
            workspace: jellywoon-xzc5r
        test: /content/yolov9/k3/test/images
        train: /content/yolov9/k3/train/images
        val: /content/yolov9/k3/valid/images
device:
    value: "0"
entity:
    value: null
epochs:
    value: 25
evolve:
    value: null
exist_ok:
    value: false
fixed_lr:
    value: false
flat_cos_lr:
    value: false
freeze:
    value:
        - 0
hyp:
    value:
        anchor_t: 5
        box: 7.5
        cls: 0.5
        cls_pw: 1
        copy_paste: 0.3
        degrees: 0
        dfl: 1.5
        fl_gamma: 0
        fliplr: 0.5
        flipud: 0
        hsv_h: 0.015
        hsv_s: 0.7
        hsv_v: 0.4
        iou_t: 0.2
        lr0: 0.01
        lrf: 0.01
        mixup: 0.15
        momentum: 0.937
        mosaic: 1
        obj_pw: 1
        perspective: 0
        scale: 0.9
        shear: 0
        translate: 0.1
        warmup_bias_lr: 0.1
        warmup_epochs: 3
        warmup_momentum: 0.8
        weight_decay: 0.0005
image_weights:
    value: false
imgsz:
    value: 640
label_smoothing:
    value: 0
local_rank:
    value: -1
min_items:
    value: 0
multi_scale:
    value: false
name:
    value: exp
noautoanchor:
    value: false
noplots:
    value: false
nosave:
    value: false
noval:
    value: false
optimizer:
    value: SGD
patience:
    value: 100
project:
    value: runs/train
quad:
    value: false
rect:
    value: false
resume:
    value: false
save_dir:
    value: runs/train/exp7
save_period:
    value: -1
seed:
    value: 0
single_cls:
    value: false
sync_bn:
    value: false
upload_dataset:
    value: false
weights:
    value: /content/weights/gelan-c.pt
workers:
    value: 8
